# Generated by Django 4.2.25 on 2025-10-07 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('document_type', models.CharField(choices=[('immigration', 'Immigration'), ('tax', 'Tax'), ('utilities', 'Utilities'), ('banking', 'Banking'), ('general', 'General')], max_length=100)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('pt', 'Portuguese'), ('gu', 'Guarani')], default='es', max_length=10)),
                ('embedding_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('residency_application', 'Residency Application'), ('power_of_attorney', 'Power of Attorney'), ('rental_contract', 'Rental Contract'), ('bank_application', 'Bank Application'), ('ande_application', 'ANDE Application')], max_length=100)),
                ('template_content', models.TextField()),
                ('fields', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_templates',
                'ordering': ['name'],
            },
        ),
    ]
