# Generated by Django 4.2.25 on 2025-10-07 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('chat', 'Chat'), ('document_generation', 'Document Generation'), ('translation', 'Translation'), ('question_answering', 'Question Answering')], max_length=50)),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_hash', models.CharField(max_length=64, unique=True)),
                ('embedding_vector', models.JSONField()),
                ('model_used', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'embedding_cache',
            },
        ),
    ]
